"""Report generator — produces intraday_brief, daily_close_report, and event_alert reports.

Reports are generated from validated MarketReportDataset.
Does NOT fabricate missing market data.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from clients.market_data_client import MarketReportDataset, Quote

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates Markdown reports from validated datasets.

    Three report types:
      - intraday_brief: Short summary, notification-first, every 2h during market.
      - daily_close_report: Full Markdown, generated after market close.
      - event_alert: Triggered by abnormal price/volume thresholds.
    """

    def __init__(
        self,
        price_change_threshold_pct: float = 3.0,
        volume_spike_ratio: float = 3.0,
    ) -> None:
        self._price_change_threshold = price_change_threshold_pct
        self._volume_spike_ratio = volume_spike_ratio

    # ── Intraday brief ──────────────────────────────────────────

    def generate_intraday_brief(self, dataset: MarketReportDataset) -> str:
        """Generate a short intraday summary (notification-first format)."""
        if not dataset.validated:
            raise ValueError(f"Dataset {dataset.run_id} must be validated before report generation")

        now = datetime.now(timezone.utc)
        market = dataset.market
        quotes = dataset.quotes
        status = dataset.market_status

        lines = [
            f"# Intraday Brief — {market}",
            f"**Time:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Session:** {status.session if status else 'unknown'}",
            f"**Symbols tracked:** {len(quotes)}",
            "",
            "## 📊 Market Snapshot",
            "",
            "| Symbol | Price | Change% | Volume | Status |",
            "|--------|-------|---------|--------|--------|",
        ]

        for q in sorted(quotes, key=lambda x: abs(x.change_percent), reverse=True):
            change_icon = "🔴" if q.change_percent < 0 else "🟢" if q.change_percent > 0 else "⚪"
            lines.append(
                f"| {q.symbol} | {q.latest_price:.2f} | "
                f"{change_icon} {q.change_percent:+.2f}% | "
                f"{q.volume:,} | {q.trade_status} |"
            )

        lines.append("")
        lines.append("## ⚡ Notable Movers")

        movers = self._detect_movers(quotes)
        if movers:
            for m in movers:
                direction = "UP" if m.change_percent > 0 else "DOWN"
                lines.append(
                    f"- **{m.symbol}**: {direction} {abs(m.change_percent):.2f}% "
                    f"({m.latest_price:.2f})"
                )
        else:
            lines.append("_No significant movers detected._")

        lines.append("")
        lines.append(f"---")
        lines.append(f"*Report ID: {dataset.run_id} | Generated by api-report-agent*")

        return "\n".join(lines)

    # ── Daily close report ───────────────────────────────────────

    def generate_daily_close_report(self, dataset: MarketReportDataset) -> str:
        """Generate a full daily close Markdown report."""
        if not dataset.validated:
            raise ValueError(f"Dataset {dataset.run_id} must be validated before report generation")

        now = datetime.now(timezone.utc)
        market = dataset.market
        quotes = dataset.quotes

        lines = [
            f"# 📈 Daily Close Report — {market}",
            f"**Date:** {now.strftime('%Y-%m-%d')}",
            f"**Generated:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Symbols tracked:** {len(quotes)}",
            "",
            "---",
            "",
            "## Market Summary",
            "",
        ]

        if not quotes:
            lines.append("_No quote data available._")
        else:
            gainers = [q for q in quotes if q.change_percent > 0]
            losers = [q for q in quotes if q.change_percent < 0]
            unchanged = [q for q in quotes if q.change_percent == 0]

            lines.append(f"- **Advancers:** {len(gainers)}")
            lines.append(f"- **Decliners:** {len(losers)}")
            lines.append(f"- **Unchanged:** {len(unchanged)}")
            lines.append("")

            lines.append("## 📊 Closing Prices")
            lines.append("")
            lines.append("| Symbol | Close | Change% | High | Low | Volume |")
            lines.append("|--------|-------|---------|------|-----|--------|")

            for q in sorted(quotes, key=lambda x: abs(x.change_percent), reverse=True):
                change_icon = "🔴" if q.change_percent < 0 else "🟢" if q.change_percent > 0 else "⚪"
                lines.append(
                    f"| {q.symbol} | {q.latest_price:.2f} | "
                    f"{change_icon} {q.change_percent:+.2f}% | "
                    f"{q.high:.2f} | {q.low:.2f} | {q.volume:,} |"
                )

            lines.append("")

            # Top movers section
            lines.append("## 🏆 Top Movers")
            lines.append("")
            top_gainers = sorted(gainers, key=lambda x: x.change_percent, reverse=True)[:5]
            top_losers = sorted(losers, key=lambda x: x.change_percent)[:5]

            if top_gainers:
                lines.append("### Gainers")
                for q in top_gainers:
                    lines.append(f"- **{q.symbol}**: +{q.change_percent:.2f}% → {q.latest_price:.2f}")

            if top_losers:
                lines.append("")
                lines.append("### Losers")
                for q in top_losers:
                    lines.append(f"- **{q.symbol}**: {q.change_percent:.2f}% → {q.latest_price:.2f}")

            lines.append("")

            # Candles summary
            if dataset.candles:
                lines.append("## 📅 Recent Candles (Last 5 Days)")
                lines.append("")
                for symbol in dataset.symbols:
                    symbol_candles = [c for c in dataset.candles if c.symbol == symbol][-5:]
                    if symbol_candles:
                        lines.append(f"### {symbol}")
                        lines.append("| Date | Open | High | Low | Close | Volume |")
                        lines.append("|------|------|------|-----|-------|--------|")
                        for c in symbol_candles:
                            lines.append(
                                f"| {c.timestamp} | {c.open:.2f} | {c.high:.2f} | "
                                f"{c.low:.2f} | {c.close:.2f} | {c.volume:,} |"
                            )
                        lines.append("")

        lines.append("---")
        lines.append(f"*Report ID: {dataset.run_id} | Generated by api-report-agent*")

        return "\n".join(lines)

    # ── Event alert ──────────────────────────────────────────────

    def generate_event_alert(self, dataset: MarketReportDataset) -> str | None:
        """Generate an event alert if thresholds are met. Returns None if no events."""
        if not dataset.validated:
            return None

        events = self._detect_events(dataset.quotes)
        if not events:
            return None

        now = datetime.now(timezone.utc)

        lines = [
            f"# 🚨 Event Alert — {dataset.market}",
            f"**Time:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Session:** {dataset.market_status.session if dataset.market_status else 'unknown'}",
            "",
            "## Triggered Events",
            "",
        ]

        for evt in events:
            lines.append(f"### {evt['symbol']}")
            for trigger in evt["triggers"]:
                lines.append(f"- {trigger}")
            lines.append(f"  - Current Price: {evt['price']:.2f}")
            lines.append(f"  - Change: {evt['change']:+.2f}%")
            lines.append(f"  - Volume: {evt['volume']:,}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Report ID: {dataset.run_id} | Immediate notification*")

        return "\n".join(lines)

    # ── Detection helpers ────────────────────────────────────────

    def _detect_movers(self, quotes: list[Quote]) -> list[Quote]:
        """Return quotes with significant price movement."""
        return [q for q in quotes if abs(q.change_percent) >= self._price_change_threshold]

    def _detect_events(self, quotes: list[Quote]) -> list[dict[str, Any]]:
        """Detect events exceeding thresholds. Returns list of event dicts."""
        events: list[dict[str, Any]] = []
        for q in quotes:
            triggers: list[str] = []

            if abs(q.change_percent) >= self._price_change_threshold:
                triggers.append(
                    f"⚠️ Price change {q.change_percent:+.2f}% exceeds threshold "
                    f"({self._price_change_threshold}%)"
                )

            if triggers:
                events.append({
                    "symbol": q.symbol,
                    "triggers": triggers,
                    "price": q.latest_price,
                    "change": q.change_percent,
                    "volume": q.volume,
                })

        return events
